
zuul:
  routes:
    #  禁止访问
    ignored-patterns: /*/private/**
    # 面向服务的路由
    service-eden:
      path: /eden/**
      retryable: false
      stripPrefix: true
      url: http://service-eden:7701
    service-bkb:
      path: /bkb/**
      retryable: false
      stripPrefix: true
      url: http://service-bkb:7002
    root:
      path: /
      url: forward:/index
    actuator:
      path: /actuator/**
      url: forward:/actuator
    error:
      path: /**
      url: forward:/unRecognize
